// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CasbinRulesColumns holds the columns for the "casbin_rules" table.
	CasbinRulesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "ptype", Type: field.TypeString, Default: ""},
		{Name: "v0", Type: field.TypeString, Default: ""},
		{Name: "v1", Type: field.TypeString, Default: ""},
		{Name: "v2", Type: field.TypeString, Default: ""},
		{Name: "v3", Type: field.TypeString, Default: ""},
		{Name: "v4", Type: field.TypeString, Default: ""},
		{Name: "v5", Type: field.TypeString, Default: ""},
	}
	// CasbinRulesTable holds the schema information for the "casbin_rules" table.
	CasbinRulesTable = &schema.Table{
		Name:       "casbin_rules",
		Columns:    CasbinRulesColumns,
		PrimaryKey: []*schema.Column{CasbinRulesColumns[0]},
	}
	// SysDepartmentsColumns holds the columns for the "sys_departments" table.
	SysDepartmentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, Comment: "The ID of the permission."},
		{Name: "name", Type: field.TypeString},
		{Name: "keyword", Type: field.TypeString, Unique: true},
		{Name: "status", Type: field.TypeInt},
		{Name: "parent_id", Type: field.TypeString, Nullable: true},
	}
	// SysDepartmentsTable holds the schema information for the "sys_departments" table.
	SysDepartmentsTable = &schema.Table{
		Name:       "sys_departments",
		Comment:    "entity.department.table.comment",
		Columns:    SysDepartmentsColumns,
		PrimaryKey: []*schema.Column{SysDepartmentsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sys_departments_sys_departments_children",
				Columns:    []*schema.Column{SysDepartmentsColumns[4]},
				RefColumns: []*schema.Column{SysDepartmentsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "department_keyword",
				Unique:  false,
				Columns: []*schema.Column{SysDepartmentsColumns[2]},
			},
			{
				Name:    "department_name",
				Unique:  false,
				Columns: []*schema.Column{SysDepartmentsColumns[1]},
			},
			{
				Name:    "department_status",
				Unique:  false,
				Columns: []*schema.Column{SysDepartmentsColumns[3]},
			},
		},
	}
	// MsgNotificationsColumns holds the columns for the "msg_notifications" table.
	MsgNotificationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, Comment: "The ID of the permission."},
		{Name: "subject", Type: field.TypeString},
		{Name: "content", Type: field.TypeString},
		{Name: "status", Type: field.TypeInt},
		{Name: "category_id", Type: field.TypeString},
	}
	// MsgNotificationsTable holds the schema information for the "msg_notifications" table.
	MsgNotificationsTable = &schema.Table{
		Name:       "msg_notifications",
		Comment:    "entity.notification.table.comment",
		Columns:    MsgNotificationsColumns,
		PrimaryKey: []*schema.Column{MsgNotificationsColumns[0]},
	}
	// SysPermissionsColumns holds the columns for the "sys_permissions" table.
	SysPermissionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, Comment: "The ID of the permission."},
		{Name: "name", Type: field.TypeString},
		{Name: "keyword", Type: field.TypeString, Unique: true},
		{Name: "data_scope", Type: field.TypeString},
	}
	// SysPermissionsTable holds the schema information for the "sys_permissions" table.
	SysPermissionsTable = &schema.Table{
		Name:       "sys_permissions",
		Comment:    "entity.permission.table.comment",
		Columns:    SysPermissionsColumns,
		PrimaryKey: []*schema.Column{SysPermissionsColumns[0]},
	}
	// SysPermissionResourcesColumns holds the columns for the "sys_permission_resources" table.
	SysPermissionResourcesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, Comment: "The ID of the permission."},
		{Name: "permission_id", Type: field.TypeString},
		{Name: "resource_id", Type: field.TypeString},
	}
	// SysPermissionResourcesTable holds the schema information for the "sys_permission_resources" table.
	SysPermissionResourcesTable = &schema.Table{
		Name:       "sys_permission_resources",
		Comment:    "entity.permission_resource.table.comment",
		Columns:    SysPermissionResourcesColumns,
		PrimaryKey: []*schema.Column{SysPermissionResourcesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sys_permission_resources_sys_permissions_permission",
				Columns:    []*schema.Column{SysPermissionResourcesColumns[1]},
				RefColumns: []*schema.Column{SysPermissionsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "sys_permission_resources_sys_resources_resource",
				Columns:    []*schema.Column{SysPermissionResourcesColumns[2]},
				RefColumns: []*schema.Column{SysResourcesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "permissionresource_permission_id_resource_id",
				Unique:  true,
				Columns: []*schema.Column{SysPermissionResourcesColumns[1], SysPermissionResourcesColumns[2]},
			},
		},
	}
	// SysPositionsColumns holds the columns for the "sys_positions" table.
	SysPositionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, Comment: "The ID of the permission."},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "keyword", Type: field.TypeString, Unique: true},
		{Name: "department_id", Type: field.TypeString},
	}
	// SysPositionsTable holds the schema information for the "sys_positions" table.
	SysPositionsTable = &schema.Table{
		Name:       "sys_positions",
		Comment:    "entity.position.table.comment",
		Columns:    SysPositionsColumns,
		PrimaryKey: []*schema.Column{SysPositionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sys_positions_sys_departments_positions",
				Columns:    []*schema.Column{SysPositionsColumns[3]},
				RefColumns: []*schema.Column{SysDepartmentsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// SysPositionPermissionsColumns holds the columns for the "sys_position_permissions" table.
	SysPositionPermissionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, Comment: "The ID of the permission."},
		{Name: "position_id", Type: field.TypeString},
		{Name: "permission_id", Type: field.TypeString},
	}
	// SysPositionPermissionsTable holds the schema information for the "sys_position_permissions" table.
	SysPositionPermissionsTable = &schema.Table{
		Name:       "sys_position_permissions",
		Comment:    "entity.position_permission.table.comment",
		Columns:    SysPositionPermissionsColumns,
		PrimaryKey: []*schema.Column{SysPositionPermissionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sys_position_permissions_sys_positions_position",
				Columns:    []*schema.Column{SysPositionPermissionsColumns[1]},
				RefColumns: []*schema.Column{SysPositionsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "sys_position_permissions_sys_permissions_permission",
				Columns:    []*schema.Column{SysPositionPermissionsColumns[2]},
				RefColumns: []*schema.Column{SysPermissionsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "positionpermission_permission_id",
				Unique:  false,
				Columns: []*schema.Column{SysPositionPermissionsColumns[2]},
			},
			{
				Name:    "positionpermission_position_id",
				Unique:  false,
				Columns: []*schema.Column{SysPositionPermissionsColumns[1]},
			},
			{
				Name:    "positionpermission_position_id_permission_id",
				Unique:  true,
				Columns: []*schema.Column{SysPositionPermissionsColumns[1], SysPositionPermissionsColumns[2]},
			},
		},
	}
	// SysResourcesColumns holds the columns for the "sys_resources" table.
	SysResourcesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, Comment: "The ID of the permission."},
		{Name: "name", Type: field.TypeString},
		{Name: "keyword", Type: field.TypeString, Unique: true},
		{Name: "type", Type: field.TypeString},
		{Name: "status", Type: field.TypeInt},
		{Name: "path", Type: field.TypeString},
		{Name: "parent_id", Type: field.TypeString, Nullable: true},
	}
	// SysResourcesTable holds the schema information for the "sys_resources" table.
	SysResourcesTable = &schema.Table{
		Name:       "sys_resources",
		Comment:    "entity.resource.table.comment",
		Columns:    SysResourcesColumns,
		PrimaryKey: []*schema.Column{SysResourcesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sys_resources_sys_resources_children",
				Columns:    []*schema.Column{SysResourcesColumns[6]},
				RefColumns: []*schema.Column{SysResourcesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "resource_parent_id",
				Unique:  false,
				Columns: []*schema.Column{SysResourcesColumns[6]},
			},
		},
	}
	// SysRolesColumns holds the columns for the "sys_roles" table.
	SysRolesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, Comment: "The ID of the permission."},
		{Name: "name", Type: field.TypeString},
		{Name: "keyword", Type: field.TypeString, Unique: true},
		{Name: "status", Type: field.TypeInt},
	}
	// SysRolesTable holds the schema information for the "sys_roles" table.
	SysRolesTable = &schema.Table{
		Name:       "sys_roles",
		Comment:    "entity.role.table.comment",
		Columns:    SysRolesColumns,
		PrimaryKey: []*schema.Column{SysRolesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "role_name",
				Unique:  false,
				Columns: []*schema.Column{SysRolesColumns[1]},
			},
			{
				Name:    "role_keyword",
				Unique:  false,
				Columns: []*schema.Column{SysRolesColumns[2]},
			},
			{
				Name:    "role_status",
				Unique:  false,
				Columns: []*schema.Column{SysRolesColumns[3]},
			},
		},
	}
	// SysRolePermissionsColumns holds the columns for the "sys_role_permissions" table.
	SysRolePermissionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, Comment: "The ID of the permission."},
		{Name: "role_id", Type: field.TypeString},
		{Name: "permission_id", Type: field.TypeString},
	}
	// SysRolePermissionsTable holds the schema information for the "sys_role_permissions" table.
	SysRolePermissionsTable = &schema.Table{
		Name:       "sys_role_permissions",
		Comment:    "entity.role_permission.table.comment",
		Columns:    SysRolePermissionsColumns,
		PrimaryKey: []*schema.Column{SysRolePermissionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sys_role_permissions_sys_roles_role",
				Columns:    []*schema.Column{SysRolePermissionsColumns[1]},
				RefColumns: []*schema.Column{SysRolesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "sys_role_permissions_sys_permissions_permission",
				Columns:    []*schema.Column{SysRolePermissionsColumns[2]},
				RefColumns: []*schema.Column{SysPermissionsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "rolepermission_role_id",
				Unique:  false,
				Columns: []*schema.Column{SysRolePermissionsColumns[1]},
			},
			{
				Name:    "rolepermission_permission_id",
				Unique:  false,
				Columns: []*schema.Column{SysRolePermissionsColumns[2]},
			},
			{
				Name:    "rolepermission_role_id_permission_id",
				Unique:  true,
				Columns: []*schema.Column{SysRolePermissionsColumns[1], SysRolePermissionsColumns[2]},
			},
		},
	}
	// SoftDeletesColumns holds the columns for the "soft_deletes" table.
	SoftDeletesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "delete_time", Type: field.TypeTime, Nullable: true},
	}
	// SoftDeletesTable holds the schema information for the "soft_deletes" table.
	SoftDeletesTable = &schema.Table{
		Name:       "soft_deletes",
		Columns:    SoftDeletesColumns,
		PrimaryKey: []*schema.Column{SoftDeletesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "softdelete_delete_time",
				Unique:  false,
				Columns: []*schema.Column{SoftDeletesColumns[1]},
			},
		},
	}
	// SysUsersColumns holds the columns for the "sys_users" table.
	SysUsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, Comment: "The ID of the permission."},
		{Name: "uuid", Type: field.TypeString, Unique: true},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "nickname", Type: field.TypeString},
		{Name: "email", Type: field.TypeString},
		{Name: "status", Type: field.TypeInt},
	}
	// SysUsersTable holds the schema information for the "sys_users" table.
	SysUsersTable = &schema.Table{
		Name:       "sys_users",
		Comment:    "entity.user.table.comment",
		Columns:    SysUsersColumns,
		PrimaryKey: []*schema.Column{SysUsersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "user_username",
				Unique:  false,
				Columns: []*schema.Column{SysUsersColumns[2]},
			},
			{
				Name:    "user_email",
				Unique:  false,
				Columns: []*schema.Column{SysUsersColumns[4]},
			},
			{
				Name:    "user_status",
				Unique:  false,
				Columns: []*schema.Column{SysUsersColumns[5]},
			},
		},
	}
	// SysUserDepartmentsColumns holds the columns for the "sys_user_departments" table.
	SysUserDepartmentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, Comment: "The ID of the permission."},
		{Name: "user_id", Type: field.TypeString},
		{Name: "department_id", Type: field.TypeString},
	}
	// SysUserDepartmentsTable holds the schema information for the "sys_user_departments" table.
	SysUserDepartmentsTable = &schema.Table{
		Name:       "sys_user_departments",
		Comment:    "entity.user_department.table.comment",
		Columns:    SysUserDepartmentsColumns,
		PrimaryKey: []*schema.Column{SysUserDepartmentsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sys_user_departments_sys_users_user",
				Columns:    []*schema.Column{SysUserDepartmentsColumns[1]},
				RefColumns: []*schema.Column{SysUsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "sys_user_departments_sys_departments_department",
				Columns:    []*schema.Column{SysUserDepartmentsColumns[2]},
				RefColumns: []*schema.Column{SysDepartmentsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "userdepartment_user_id",
				Unique:  false,
				Columns: []*schema.Column{SysUserDepartmentsColumns[1]},
			},
			{
				Name:    "userdepartment_department_id",
				Unique:  false,
				Columns: []*schema.Column{SysUserDepartmentsColumns[2]},
			},
			{
				Name:    "userdepartment_user_id_department_id",
				Unique:  true,
				Columns: []*schema.Column{SysUserDepartmentsColumns[1], SysUserDepartmentsColumns[2]},
			},
		},
	}
	// SysUserPositionsColumns holds the columns for the "sys_user_positions" table.
	SysUserPositionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, Comment: "The ID of the permission."},
		{Name: "user_id", Type: field.TypeString},
		{Name: "position_id", Type: field.TypeString},
	}
	// SysUserPositionsTable holds the schema information for the "sys_user_positions" table.
	SysUserPositionsTable = &schema.Table{
		Name:       "sys_user_positions",
		Comment:    "entity.user_position.table.comment",
		Columns:    SysUserPositionsColumns,
		PrimaryKey: []*schema.Column{SysUserPositionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sys_user_positions_sys_users_user",
				Columns:    []*schema.Column{SysUserPositionsColumns[1]},
				RefColumns: []*schema.Column{SysUsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "sys_user_positions_sys_positions_position",
				Columns:    []*schema.Column{SysUserPositionsColumns[2]},
				RefColumns: []*schema.Column{SysPositionsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "userposition_user_id",
				Unique:  false,
				Columns: []*schema.Column{SysUserPositionsColumns[1]},
			},
			{
				Name:    "userposition_position_id",
				Unique:  false,
				Columns: []*schema.Column{SysUserPositionsColumns[2]},
			},
			{
				Name:    "userposition_user_id_position_id",
				Unique:  true,
				Columns: []*schema.Column{SysUserPositionsColumns[1], SysUserPositionsColumns[2]},
			},
		},
	}
	// SysUserRolesColumns holds the columns for the "sys_user_roles" table.
	SysUserRolesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, Comment: "The ID of the permission."},
		{Name: "user_id", Type: field.TypeString},
		{Name: "role_id", Type: field.TypeString},
	}
	// SysUserRolesTable holds the schema information for the "sys_user_roles" table.
	SysUserRolesTable = &schema.Table{
		Name:       "sys_user_roles",
		Comment:    "entity.(1).(2).(3)",
		Columns:    SysUserRolesColumns,
		PrimaryKey: []*schema.Column{SysUserRolesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sys_user_roles_sys_users_user",
				Columns:    []*schema.Column{SysUserRolesColumns[1]},
				RefColumns: []*schema.Column{SysUsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "sys_user_roles_sys_roles_role",
				Columns:    []*schema.Column{SysUserRolesColumns[2]},
				RefColumns: []*schema.Column{SysRolesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "userrole_user_id",
				Unique:  false,
				Columns: []*schema.Column{SysUserRolesColumns[1]},
			},
			{
				Name:    "userrole_role_id",
				Unique:  false,
				Columns: []*schema.Column{SysUserRolesColumns[2]},
			},
			{
				Name:    "userrole_user_id_role_id",
				Unique:  true,
				Columns: []*schema.Column{SysUserRolesColumns[1], SysUserRolesColumns[2]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CasbinRulesTable,
		SysDepartmentsTable,
		MsgNotificationsTable,
		SysPermissionsTable,
		SysPermissionResourcesTable,
		SysPositionsTable,
		SysPositionPermissionsTable,
		SysResourcesTable,
		SysRolesTable,
		SysRolePermissionsTable,
		SoftDeletesTable,
		SysUsersTable,
		SysUserDepartmentsTable,
		SysUserPositionsTable,
		SysUserRolesTable,
	}
)

func init() {
	SysDepartmentsTable.ForeignKeys[0].RefTable = SysDepartmentsTable
	SysDepartmentsTable.Annotation = &entsql.Annotation{
		Table: "sys_departments",
	}
	MsgNotificationsTable.Annotation = &entsql.Annotation{
		Table: "msg_notifications",
	}
	SysPermissionsTable.Annotation = &entsql.Annotation{
		Table: "sys_permissions",
	}
	SysPermissionResourcesTable.ForeignKeys[0].RefTable = SysPermissionsTable
	SysPermissionResourcesTable.ForeignKeys[1].RefTable = SysResourcesTable
	SysPermissionResourcesTable.Annotation = &entsql.Annotation{
		Table: "sys_permission_resources",
	}
	SysPositionsTable.ForeignKeys[0].RefTable = SysDepartmentsTable
	SysPositionsTable.Annotation = &entsql.Annotation{
		Table: "sys_positions",
	}
	SysPositionPermissionsTable.ForeignKeys[0].RefTable = SysPositionsTable
	SysPositionPermissionsTable.ForeignKeys[1].RefTable = SysPermissionsTable
	SysPositionPermissionsTable.Annotation = &entsql.Annotation{
		Table: "sys_position_permissions",
	}
	SysResourcesTable.ForeignKeys[0].RefTable = SysResourcesTable
	SysResourcesTable.Annotation = &entsql.Annotation{
		Table: "sys_resources",
	}
	SysRolesTable.Annotation = &entsql.Annotation{
		Table: "sys_roles",
	}
	SysRolePermissionsTable.ForeignKeys[0].RefTable = SysRolesTable
	SysRolePermissionsTable.ForeignKeys[1].RefTable = SysPermissionsTable
	SysRolePermissionsTable.Annotation = &entsql.Annotation{
		Table: "sys_role_permissions",
	}
	SysUsersTable.Annotation = &entsql.Annotation{
		Table: "sys_users",
	}
	SysUserDepartmentsTable.ForeignKeys[0].RefTable = SysUsersTable
	SysUserDepartmentsTable.ForeignKeys[1].RefTable = SysDepartmentsTable
	SysUserDepartmentsTable.Annotation = &entsql.Annotation{
		Table: "sys_user_departments",
	}
	SysUserPositionsTable.ForeignKeys[0].RefTable = SysUsersTable
	SysUserPositionsTable.ForeignKeys[1].RefTable = SysPositionsTable
	SysUserPositionsTable.Annotation = &entsql.Annotation{
		Table: "sys_user_positions",
	}
	SysUserRolesTable.ForeignKeys[0].RefTable = SysUsersTable
	SysUserRolesTable.ForeignKeys[1].RefTable = SysRolesTable
	SysUserRolesTable.Annotation = &entsql.Annotation{
		Table: "sys_user_roles",
	}
}
