package test_menu_pb_issue

import (
	"context"
)

// MenuRepo is a Menu repository interface that references MenuPB
// which will be generated by abgen
type MenuRepo interface {
	Get(context.Context, int64) (*MenuPB, error)
	Create(context.Context, *MenuPB) (*MenuPB, error)
	Delete(context.Context, int64) error
	Update(context.Context, *MenuPB) (*MenuPB, error)
	List(context.Context, *ListMenusRequest) ([]*MenuPB, int32, error)
}

// ListMenusRequest is a request type that also references MenuPB
type ListMenusRequest struct {
	Page int32
	Size int32
}

//go:abgen:package:path=github.com/origadmin/ent,alias=ent
//go:abgen:package:path=github.com/origadmin/pb,alias=pb
//go:abgen:pair:packages="ent,pb"
//go:abgen:convert:target:suffix="PB"

// Expected: MenuPB should be generated as: type MenuPB = pb.Menu
// and the interface above should compile without errors