// Code generated by abgen. DO NOT EDIT.
// versions:
// 	abgen v0.0.1

package testdata

import (
	ent "github.com/origadmin/abgen/internal/testdata/ent"
	typespb "github.com/origadmin/abgen/internal/testdata/typespb"
	slog "log/slog"
)

// Auto-generated type aliases.
type RolePB = typespb.Role
type RolePB = typespb.Role

// ConvertUserPBToUser converts *UserPB to *User.
func ConvertUserPBToUser(src *UserPB) *User {
	if src == nil {
		return nil
	}
	dst := &User{}
	dst.ID = src.ID
	dst.Username = src.Username
	
	
	dst.Age = src.Age
	dst.Status = ConvertString2Status(src.Status)
	return dst
}

// ConvertRoleToRolePB converts *Role to *RolePB.
func ConvertRoleToRolePB(src *Role) *RolePB {
	if src == nil {
		return nil
	}
	dst := &RolePB{}
	dst.ID = src.ID
	dst.Name = src.Name
	return dst
}

// ConvertRolePBToRole converts *RolePB to *Role.
func ConvertRolePBToRole(src *RolePB) *Role {
	if src == nil {
		return nil
	}
	dst := &Role{}
	dst.ID = src.ID
	dst.Name = src.Name
	return dst
}

// ConvertUserToUserPB converts *User to *UserPB.
func ConvertUserToUserPB(src *User) *UserPB {
	if src == nil {
		return nil
	}
	dst := &UserPB{}
	dst.ID = src.ID
	dst.Username = src.Username
	
	
	dst.Age = src.Age
	dst.Status = ConvertStatusToString(src.Status)
	return dst
}

// --- Auto-generated Custom Rule Helper Functions (DUMMY IMPLEMENTATIONS) ---
// These functions are placeholders for custom conversion logic defined in rules.
// You should provide actual implementations for these in your project.
func ConvertStatusToString(src interface{}) interface{} {
	// TODO: Implement the actual conversion logic for ConvertStatusToString
	// Example:
	// if src == nil {
	// 	return nil
	// }
	// // Perform conversion from source type to target type
	// return src // Placeholder: returns source as is
	panic("Not implemented: Custom rule function ConvertStatusToString")
}
func ConvertString2Status(src interface{}) interface{} {
	// TODO: Implement the actual conversion logic for ConvertString2Status
	// Example:
	// if src == nil {
	// 	return nil
	// }
	// // Perform conversion from source type to target type
	// return src // Placeholder: returns source as is
	panic("Not implemented: Custom rule function ConvertString2Status")
}