// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"github.com/origadmin/abgen/testdata/ent/permission"
	"github.com/origadmin/abgen/testdata/ent/permissionresource"
	"github.com/origadmin/abgen/testdata/ent/position"
	"github.com/origadmin/abgen/testdata/ent/positionpermission"
	"github.com/origadmin/abgen/testdata/ent/resource"
	"github.com/origadmin/abgen/testdata/ent/role"
	"github.com/origadmin/abgen/testdata/ent/rolepermission"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PermissionCreate is the builder for creating a Permission entity.
type PermissionCreate struct {
	config
	mutation *PermissionMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *PermissionCreate) SetName(v string) *PermissionCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetKeyword sets the "keyword" field.
func (_c *PermissionCreate) SetKeyword(v string) *PermissionCreate {
	_c.mutation.SetKeyword(v)
	return _c
}

// SetDataScope sets the "data_scope" field.
func (_c *PermissionCreate) SetDataScope(v string) *PermissionCreate {
	_c.mutation.SetDataScope(v)
	return _c
}

// SetID sets the "id" field.
func (_c *PermissionCreate) SetID(v string) *PermissionCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddRoleIDs adds the "roles" edge to the Role entity by IDs.
func (_c *PermissionCreate) AddRoleIDs(ids ...string) *PermissionCreate {
	_c.mutation.AddRoleIDs(ids...)
	return _c
}

// AddRoles adds the "roles" edges to the Role entity.
func (_c *PermissionCreate) AddRoles(v ...*Role) *PermissionCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddRoleIDs(ids...)
}

// AddPositionIDs adds the "positions" edge to the Position entity by IDs.
func (_c *PermissionCreate) AddPositionIDs(ids ...string) *PermissionCreate {
	_c.mutation.AddPositionIDs(ids...)
	return _c
}

// AddPositions adds the "positions" edges to the Position entity.
func (_c *PermissionCreate) AddPositions(v ...*Position) *PermissionCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPositionIDs(ids...)
}

// AddResourceIDs adds the "resources" edge to the Resource entity by IDs.
func (_c *PermissionCreate) AddResourceIDs(ids ...string) *PermissionCreate {
	_c.mutation.AddResourceIDs(ids...)
	return _c
}

// AddResources adds the "resources" edges to the Resource entity.
func (_c *PermissionCreate) AddResources(v ...*Resource) *PermissionCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddResourceIDs(ids...)
}

// AddRolePermissionIDs adds the "role_permissions" edge to the RolePermission entity by IDs.
func (_c *PermissionCreate) AddRolePermissionIDs(ids ...string) *PermissionCreate {
	_c.mutation.AddRolePermissionIDs(ids...)
	return _c
}

// AddRolePermissions adds the "role_permissions" edges to the RolePermission entity.
func (_c *PermissionCreate) AddRolePermissions(v ...*RolePermission) *PermissionCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddRolePermissionIDs(ids...)
}

// AddPositionPermissionIDs adds the "position_permissions" edge to the PositionPermission entity by IDs.
func (_c *PermissionCreate) AddPositionPermissionIDs(ids ...string) *PermissionCreate {
	_c.mutation.AddPositionPermissionIDs(ids...)
	return _c
}

// AddPositionPermissions adds the "position_permissions" edges to the PositionPermission entity.
func (_c *PermissionCreate) AddPositionPermissions(v ...*PositionPermission) *PermissionCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPositionPermissionIDs(ids...)
}

// AddPermissionResourceIDs adds the "permission_resources" edge to the PermissionResource entity by IDs.
func (_c *PermissionCreate) AddPermissionResourceIDs(ids ...string) *PermissionCreate {
	_c.mutation.AddPermissionResourceIDs(ids...)
	return _c
}

// AddPermissionResources adds the "permission_resources" edges to the PermissionResource entity.
func (_c *PermissionCreate) AddPermissionResources(v ...*PermissionResource) *PermissionCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPermissionResourceIDs(ids...)
}

// Mutation returns the PermissionMutation object of the builder.
func (_c *PermissionCreate) Mutation() *PermissionMutation {
	return _c.mutation
}

// Save creates the Permission in the database.
func (_c *PermissionCreate) Save(ctx context.Context) (*Permission, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PermissionCreate) SaveX(ctx context.Context) *Permission {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PermissionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PermissionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PermissionCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Permission.name"`)}
	}
	if _, ok := _c.mutation.Keyword(); !ok {
		return &ValidationError{Name: "keyword", err: errors.New(`ent: missing required field "Permission.keyword"`)}
	}
	if _, ok := _c.mutation.DataScope(); !ok {
		return &ValidationError{Name: "data_scope", err: errors.New(`ent: missing required field "Permission.data_scope"`)}
	}
	return nil
}

func (_c *PermissionCreate) sqlSave(ctx context.Context) (*Permission, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Permission.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PermissionCreate) createSpec() (*Permission, *sqlgraph.CreateSpec) {
	var (
		_node = &Permission{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(permission.Table, sqlgraph.NewFieldSpec(permission.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(permission.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Keyword(); ok {
		_spec.SetField(permission.FieldKeyword, field.TypeString, value)
		_node.Keyword = value
	}
	if value, ok := _c.mutation.DataScope(); ok {
		_spec.SetField(permission.FieldDataScope, field.TypeString, value)
		_node.DataScope = value
	}
	if nodes := _c.mutation.RolesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   permission.RolesTable,
			Columns: permission.RolesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PositionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   permission.PositionsTable,
			Columns: permission.PositionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(position.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ResourcesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   permission.ResourcesTable,
			Columns: permission.ResourcesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resource.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RolePermissionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   permission.RolePermissionsTable,
			Columns: []string{permission.RolePermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rolepermission.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PositionPermissionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   permission.PositionPermissionsTable,
			Columns: []string{permission.PositionPermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(positionpermission.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PermissionResourcesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   permission.PermissionResourcesTable,
			Columns: []string{permission.PermissionResourcesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(permissionresource.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SetPermission set the Permission
func (_c *PermissionCreate) SetPermission(input *Permission, fields ...string) *PermissionCreate {
	m := _c.mutation
	if len(fields) == 0 {
		fields = permission.Columns
	}
	_ = m.SetFields(input, fields...)
	return _c
}

// SetPermissionWithZero set the Permission
func (_c *PermissionCreate) SetPermissionWithZero(input *Permission, fields ...string) *PermissionCreate {
	m := _c.mutation
	if len(fields) == 0 {
		fields = permission.Columns
	}
	_ = m.SetFieldsWithZero(input, fields...)
	return _c
}

// PermissionCreateBulk is the builder for creating many Permission entities in bulk.
type PermissionCreateBulk struct {
	config
	err      error
	builders []*PermissionCreate
}

// Save creates the Permission entities in the database.
func (_c *PermissionCreateBulk) Save(ctx context.Context) ([]*Permission, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Permission, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PermissionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PermissionCreateBulk) SaveX(ctx context.Context) []*Permission {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PermissionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PermissionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
