// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"github.com/origadmin/abgen/testdata/ent/department"
	"github.com/origadmin/abgen/testdata/ent/permission"
	"github.com/origadmin/abgen/testdata/ent/position"
	"github.com/origadmin/abgen/testdata/ent/positionpermission"
	"github.com/origadmin/abgen/testdata/ent/user"
	"github.com/origadmin/abgen/testdata/ent/userposition"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PositionCreate is the builder for creating a Position entity.
type PositionCreate struct {
	config
	mutation *PositionMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *PositionCreate) SetName(v string) *PositionCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetKeyword sets the "keyword" field.
func (_c *PositionCreate) SetKeyword(v string) *PositionCreate {
	_c.mutation.SetKeyword(v)
	return _c
}

// SetDepartmentID sets the "department_id" field.
func (_c *PositionCreate) SetDepartmentID(v string) *PositionCreate {
	_c.mutation.SetDepartmentID(v)
	return _c
}

// SetID sets the "id" field.
func (_c *PositionCreate) SetID(v string) *PositionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetDepartment sets the "department" edge to the Department entity.
func (_c *PositionCreate) SetDepartment(v *Department) *PositionCreate {
	return _c.SetDepartmentID(v.ID)
}

// AddUserIDs adds the "users" edge to the User entity by IDs.
func (_c *PositionCreate) AddUserIDs(ids ...string) *PositionCreate {
	_c.mutation.AddUserIDs(ids...)
	return _c
}

// AddUsers adds the "users" edges to the User entity.
func (_c *PositionCreate) AddUsers(v ...*User) *PositionCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddUserIDs(ids...)
}

// AddPermissionIDs adds the "permissions" edge to the Permission entity by IDs.
func (_c *PositionCreate) AddPermissionIDs(ids ...string) *PositionCreate {
	_c.mutation.AddPermissionIDs(ids...)
	return _c
}

// AddPermissions adds the "permissions" edges to the Permission entity.
func (_c *PositionCreate) AddPermissions(v ...*Permission) *PositionCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPermissionIDs(ids...)
}

// AddUserPositionIDs adds the "user_positions" edge to the UserPosition entity by IDs.
func (_c *PositionCreate) AddUserPositionIDs(ids ...string) *PositionCreate {
	_c.mutation.AddUserPositionIDs(ids...)
	return _c
}

// AddUserPositions adds the "user_positions" edges to the UserPosition entity.
func (_c *PositionCreate) AddUserPositions(v ...*UserPosition) *PositionCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddUserPositionIDs(ids...)
}

// AddPositionPermissionIDs adds the "position_permissions" edge to the PositionPermission entity by IDs.
func (_c *PositionCreate) AddPositionPermissionIDs(ids ...string) *PositionCreate {
	_c.mutation.AddPositionPermissionIDs(ids...)
	return _c
}

// AddPositionPermissions adds the "position_permissions" edges to the PositionPermission entity.
func (_c *PositionCreate) AddPositionPermissions(v ...*PositionPermission) *PositionCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPositionPermissionIDs(ids...)
}

// Mutation returns the PositionMutation object of the builder.
func (_c *PositionCreate) Mutation() *PositionMutation {
	return _c.mutation
}

// Save creates the Position in the database.
func (_c *PositionCreate) Save(ctx context.Context) (*Position, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PositionCreate) SaveX(ctx context.Context) *Position {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PositionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PositionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PositionCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Position.name"`)}
	}
	if _, ok := _c.mutation.Keyword(); !ok {
		return &ValidationError{Name: "keyword", err: errors.New(`ent: missing required field "Position.keyword"`)}
	}
	if _, ok := _c.mutation.DepartmentID(); !ok {
		return &ValidationError{Name: "department_id", err: errors.New(`ent: missing required field "Position.department_id"`)}
	}
	if len(_c.mutation.DepartmentIDs()) == 0 {
		return &ValidationError{Name: "department", err: errors.New(`ent: missing required edge "Position.department"`)}
	}
	return nil
}

func (_c *PositionCreate) sqlSave(ctx context.Context) (*Position, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Position.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PositionCreate) createSpec() (*Position, *sqlgraph.CreateSpec) {
	var (
		_node = &Position{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(position.Table, sqlgraph.NewFieldSpec(position.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(position.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Keyword(); ok {
		_spec.SetField(position.FieldKeyword, field.TypeString, value)
		_node.Keyword = value
	}
	if nodes := _c.mutation.DepartmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   position.DepartmentTable,
			Columns: []string{position.DepartmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(department.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.DepartmentID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   position.UsersTable,
			Columns: position.UsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PermissionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   position.PermissionsTable,
			Columns: position.PermissionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(permission.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserPositionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   position.UserPositionsTable,
			Columns: []string{position.UserPositionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userposition.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PositionPermissionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   position.PositionPermissionsTable,
			Columns: []string{position.PositionPermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(positionpermission.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SetPosition set the Position
func (_c *PositionCreate) SetPosition(input *Position, fields ...string) *PositionCreate {
	m := _c.mutation
	if len(fields) == 0 {
		fields = position.Columns
	}
	_ = m.SetFields(input, fields...)
	return _c
}

// SetPositionWithZero set the Position
func (_c *PositionCreate) SetPositionWithZero(input *Position, fields ...string) *PositionCreate {
	m := _c.mutation
	if len(fields) == 0 {
		fields = position.Columns
	}
	_ = m.SetFieldsWithZero(input, fields...)
	return _c
}

// PositionCreateBulk is the builder for creating many Position entities in bulk.
type PositionCreateBulk struct {
	config
	err      error
	builders []*PositionCreate
}

// Save creates the Position entities in the database.
func (_c *PositionCreateBulk) Save(ctx context.Context) ([]*Position, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Position, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PositionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PositionCreateBulk) SaveX(ctx context.Context) []*Position {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PositionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PositionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
