// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"github.com/origadmin/abgen/testdata/ent/department"
	"github.com/origadmin/abgen/testdata/ent/position"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// entity.position.table.comment
type Position struct {
	config `json:"-"`
	// ID of the ent.
	// The ID of the permission.
	ID string `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Keyword holds the value of the "keyword" field.
	Keyword string `json:"keyword,omitempty"`
	// DepartmentID holds the value of the "department_id" field.
	DepartmentID string `json:"department_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PositionQuery when eager-loading is set.
	Edges        PositionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PositionEdges holds the relations/edges for other nodes in the graph.
type PositionEdges struct {
	// Department holds the value of the department edge.
	Department *Department `json:"department,omitempty"`
	// Users holds the value of the users edge.
	Users []*User `json:"users,omitempty"`
	// Permissions holds the value of the permissions edge.
	Permissions []*Permission `json:"permissions,omitempty"`
	// UserPositions holds the value of the user_positions edge.
	UserPositions []*UserPosition `json:"user_positions,omitempty"`
	// PositionPermissions holds the value of the position_permissions edge.
	PositionPermissions []*PositionPermission `json:"position_permissions,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [5]bool
}

// DepartmentOrErr returns the Department value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PositionEdges) DepartmentOrErr() (*Department, error) {
	if e.Department != nil {
		return e.Department, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: department.Label}
	}
	return nil, &NotLoadedError{edge: "department"}
}

// UsersOrErr returns the Users value or an error if the edge
// was not loaded in eager-loading.
func (e PositionEdges) UsersOrErr() ([]*User, error) {
	if e.loadedTypes[1] {
		return e.Users, nil
	}
	return nil, &NotLoadedError{edge: "users"}
}

// PermissionsOrErr returns the Permissions value or an error if the edge
// was not loaded in eager-loading.
func (e PositionEdges) PermissionsOrErr() ([]*Permission, error) {
	if e.loadedTypes[2] {
		return e.Permissions, nil
	}
	return nil, &NotLoadedError{edge: "permissions"}
}

// UserPositionsOrErr returns the UserPositions value or an error if the edge
// was not loaded in eager-loading.
func (e PositionEdges) UserPositionsOrErr() ([]*UserPosition, error) {
	if e.loadedTypes[3] {
		return e.UserPositions, nil
	}
	return nil, &NotLoadedError{edge: "user_positions"}
}

// PositionPermissionsOrErr returns the PositionPermissions value or an error if the edge
// was not loaded in eager-loading.
func (e PositionEdges) PositionPermissionsOrErr() ([]*PositionPermission, error) {
	if e.loadedTypes[4] {
		return e.PositionPermissions, nil
	}
	return nil, &NotLoadedError{edge: "position_permissions"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Position) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case position.FieldID, position.FieldName, position.FieldKeyword, position.FieldDepartmentID:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Position fields.
func (_m *Position) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case position.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case position.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case position.FieldKeyword:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field keyword", values[i])
			} else if value.Valid {
				_m.Keyword = value.String
			}
		case position.FieldDepartmentID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field department_id", values[i])
			} else if value.Valid {
				_m.DepartmentID = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Position.
// This includes values selected through modifiers, order, etc.
func (_m *Position) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryDepartment queries the "department" edge of the Position entity.
func (_m *Position) QueryDepartment() *DepartmentQuery {
	return NewPositionClient(_m.config).QueryDepartment(_m)
}

// QueryUsers queries the "users" edge of the Position entity.
func (_m *Position) QueryUsers() *UserQuery {
	return NewPositionClient(_m.config).QueryUsers(_m)
}

// QueryPermissions queries the "permissions" edge of the Position entity.
func (_m *Position) QueryPermissions() *PermissionQuery {
	return NewPositionClient(_m.config).QueryPermissions(_m)
}

// QueryUserPositions queries the "user_positions" edge of the Position entity.
func (_m *Position) QueryUserPositions() *UserPositionQuery {
	return NewPositionClient(_m.config).QueryUserPositions(_m)
}

// QueryPositionPermissions queries the "position_permissions" edge of the Position entity.
func (_m *Position) QueryPositionPermissions() *PositionPermissionQuery {
	return NewPositionClient(_m.config).QueryPositionPermissions(_m)
}

// Update returns a builder for updating this Position.
// Note that you need to call Position.Unwrap() before calling this method if this Position
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Position) Update() *PositionUpdateOne {
	return NewPositionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Position entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Position) Unwrap() *Position {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Position is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Position) String() string {
	var builder strings.Builder
	builder.WriteString("Position(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("keyword=")
	builder.WriteString(_m.Keyword)
	builder.WriteString(", ")
	builder.WriteString("department_id=")
	builder.WriteString(_m.DepartmentID)
	builder.WriteByte(')')
	return builder.String()
}

// Positions is a parsable slice of Position.
type Positions []*Position
