// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"github.com/origadmin/abgen/testdata/ent/permission"
	"github.com/origadmin/abgen/testdata/ent/permissionresource"
	"github.com/origadmin/abgen/testdata/ent/predicate"
	"github.com/origadmin/abgen/testdata/ent/resource"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ResourceUpdate is the builder for updating Resource entities.
type ResourceUpdate struct {
	config
	hooks     []Hook
	mutation  *ResourceMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ResourceUpdate builder.
func (_u *ResourceUpdate) Where(ps ...predicate.Resource) *ResourceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *ResourceUpdate) SetName(v string) *ResourceUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ResourceUpdate) SetNillableName(v *string) *ResourceUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetKeyword sets the "keyword" field.
func (_u *ResourceUpdate) SetKeyword(v string) *ResourceUpdate {
	_u.mutation.SetKeyword(v)
	return _u
}

// SetNillableKeyword sets the "keyword" field if the given value is not nil.
func (_u *ResourceUpdate) SetNillableKeyword(v *string) *ResourceUpdate {
	if v != nil {
		_u.SetKeyword(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *ResourceUpdate) SetType(v string) *ResourceUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *ResourceUpdate) SetNillableType(v *string) *ResourceUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ResourceUpdate) SetStatus(v int) *ResourceUpdate {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ResourceUpdate) SetNillableStatus(v *int) *ResourceUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *ResourceUpdate) AddStatus(v int) *ResourceUpdate {
	_u.mutation.AddStatus(v)
	return _u
}

// SetPath sets the "path" field.
func (_u *ResourceUpdate) SetPath(v string) *ResourceUpdate {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *ResourceUpdate) SetNillablePath(v *string) *ResourceUpdate {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetParentID sets the "parent_id" field.
func (_u *ResourceUpdate) SetParentID(v string) *ResourceUpdate {
	_u.mutation.SetParentID(v)
	return _u
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_u *ResourceUpdate) SetNillableParentID(v *string) *ResourceUpdate {
	if v != nil {
		_u.SetParentID(*v)
	}
	return _u
}

// ClearParentID clears the value of the "parent_id" field.
func (_u *ResourceUpdate) ClearParentID() *ResourceUpdate {
	_u.mutation.ClearParentID()
	return _u
}

// AddChildIDs adds the "children" edge to the Resource entity by IDs.
func (_u *ResourceUpdate) AddChildIDs(ids ...string) *ResourceUpdate {
	_u.mutation.AddChildIDs(ids...)
	return _u
}

// AddChildren adds the "children" edges to the Resource entity.
func (_u *ResourceUpdate) AddChildren(v ...*Resource) *ResourceUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChildIDs(ids...)
}

// SetParent sets the "parent" edge to the Resource entity.
func (_u *ResourceUpdate) SetParent(v *Resource) *ResourceUpdate {
	return _u.SetParentID(v.ID)
}

// AddPermissionIDs adds the "permissions" edge to the Permission entity by IDs.
func (_u *ResourceUpdate) AddPermissionIDs(ids ...string) *ResourceUpdate {
	_u.mutation.AddPermissionIDs(ids...)
	return _u
}

// AddPermissions adds the "permissions" edges to the Permission entity.
func (_u *ResourceUpdate) AddPermissions(v ...*Permission) *ResourceUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPermissionIDs(ids...)
}

// AddPermissionResourceIDs adds the "permission_resources" edge to the PermissionResource entity by IDs.
func (_u *ResourceUpdate) AddPermissionResourceIDs(ids ...string) *ResourceUpdate {
	_u.mutation.AddPermissionResourceIDs(ids...)
	return _u
}

// AddPermissionResources adds the "permission_resources" edges to the PermissionResource entity.
func (_u *ResourceUpdate) AddPermissionResources(v ...*PermissionResource) *ResourceUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPermissionResourceIDs(ids...)
}

// Mutation returns the ResourceMutation object of the builder.
func (_u *ResourceUpdate) Mutation() *ResourceMutation {
	return _u.mutation
}

// ClearChildren clears all "children" edges to the Resource entity.
func (_u *ResourceUpdate) ClearChildren() *ResourceUpdate {
	_u.mutation.ClearChildren()
	return _u
}

// RemoveChildIDs removes the "children" edge to Resource entities by IDs.
func (_u *ResourceUpdate) RemoveChildIDs(ids ...string) *ResourceUpdate {
	_u.mutation.RemoveChildIDs(ids...)
	return _u
}

// RemoveChildren removes "children" edges to Resource entities.
func (_u *ResourceUpdate) RemoveChildren(v ...*Resource) *ResourceUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChildIDs(ids...)
}

// ClearParent clears the "parent" edge to the Resource entity.
func (_u *ResourceUpdate) ClearParent() *ResourceUpdate {
	_u.mutation.ClearParent()
	return _u
}

// ClearPermissions clears all "permissions" edges to the Permission entity.
func (_u *ResourceUpdate) ClearPermissions() *ResourceUpdate {
	_u.mutation.ClearPermissions()
	return _u
}

// RemovePermissionIDs removes the "permissions" edge to Permission entities by IDs.
func (_u *ResourceUpdate) RemovePermissionIDs(ids ...string) *ResourceUpdate {
	_u.mutation.RemovePermissionIDs(ids...)
	return _u
}

// RemovePermissions removes "permissions" edges to Permission entities.
func (_u *ResourceUpdate) RemovePermissions(v ...*Permission) *ResourceUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePermissionIDs(ids...)
}

// ClearPermissionResources clears all "permission_resources" edges to the PermissionResource entity.
func (_u *ResourceUpdate) ClearPermissionResources() *ResourceUpdate {
	_u.mutation.ClearPermissionResources()
	return _u
}

// RemovePermissionResourceIDs removes the "permission_resources" edge to PermissionResource entities by IDs.
func (_u *ResourceUpdate) RemovePermissionResourceIDs(ids ...string) *ResourceUpdate {
	_u.mutation.RemovePermissionResourceIDs(ids...)
	return _u
}

// RemovePermissionResources removes "permission_resources" edges to PermissionResource entities.
func (_u *ResourceUpdate) RemovePermissionResources(v ...*PermissionResource) *ResourceUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePermissionResourceIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ResourceUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ResourceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ResourceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ResourceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ResourceUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ResourceUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ResourceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(resource.Table, resource.Columns, sqlgraph.NewFieldSpec(resource.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(resource.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Keyword(); ok {
		_spec.SetField(resource.FieldKeyword, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(resource.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(resource.FieldStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(resource.FieldStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(resource.FieldPath, field.TypeString, value)
	}
	if _u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resource.ChildrenTable,
			Columns: []string{resource.ChildrenColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resource.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !_u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resource.ChildrenTable,
			Columns: []string{resource.ChildrenColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resource.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resource.ChildrenTable,
			Columns: []string{resource.ChildrenColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resource.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   resource.ParentTable,
			Columns: []string{resource.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resource.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   resource.ParentTable,
			Columns: []string{resource.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resource.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   resource.PermissionsTable,
			Columns: resource.PermissionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(permission.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPermissionsIDs(); len(nodes) > 0 && !_u.mutation.PermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   resource.PermissionsTable,
			Columns: resource.PermissionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(permission.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PermissionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   resource.PermissionsTable,
			Columns: resource.PermissionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(permission.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PermissionResourcesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   resource.PermissionResourcesTable,
			Columns: []string{resource.PermissionResourcesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(permissionresource.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPermissionResourcesIDs(); len(nodes) > 0 && !_u.mutation.PermissionResourcesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   resource.PermissionResourcesTable,
			Columns: []string{resource.PermissionResourcesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(permissionresource.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PermissionResourcesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   resource.PermissionResourcesTable,
			Columns: []string{resource.PermissionResourcesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(permissionresource.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{resource.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ResourceUpdateOne is the builder for updating a single Resource entity.
type ResourceUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ResourceMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetName sets the "name" field.
func (_u *ResourceUpdateOne) SetName(v string) *ResourceUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ResourceUpdateOne) SetNillableName(v *string) *ResourceUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetKeyword sets the "keyword" field.
func (_u *ResourceUpdateOne) SetKeyword(v string) *ResourceUpdateOne {
	_u.mutation.SetKeyword(v)
	return _u
}

// SetNillableKeyword sets the "keyword" field if the given value is not nil.
func (_u *ResourceUpdateOne) SetNillableKeyword(v *string) *ResourceUpdateOne {
	if v != nil {
		_u.SetKeyword(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *ResourceUpdateOne) SetType(v string) *ResourceUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *ResourceUpdateOne) SetNillableType(v *string) *ResourceUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ResourceUpdateOne) SetStatus(v int) *ResourceUpdateOne {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ResourceUpdateOne) SetNillableStatus(v *int) *ResourceUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *ResourceUpdateOne) AddStatus(v int) *ResourceUpdateOne {
	_u.mutation.AddStatus(v)
	return _u
}

// SetPath sets the "path" field.
func (_u *ResourceUpdateOne) SetPath(v string) *ResourceUpdateOne {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *ResourceUpdateOne) SetNillablePath(v *string) *ResourceUpdateOne {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetParentID sets the "parent_id" field.
func (_u *ResourceUpdateOne) SetParentID(v string) *ResourceUpdateOne {
	_u.mutation.SetParentID(v)
	return _u
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_u *ResourceUpdateOne) SetNillableParentID(v *string) *ResourceUpdateOne {
	if v != nil {
		_u.SetParentID(*v)
	}
	return _u
}

// ClearParentID clears the value of the "parent_id" field.
func (_u *ResourceUpdateOne) ClearParentID() *ResourceUpdateOne {
	_u.mutation.ClearParentID()
	return _u
}

// AddChildIDs adds the "children" edge to the Resource entity by IDs.
func (_u *ResourceUpdateOne) AddChildIDs(ids ...string) *ResourceUpdateOne {
	_u.mutation.AddChildIDs(ids...)
	return _u
}

// AddChildren adds the "children" edges to the Resource entity.
func (_u *ResourceUpdateOne) AddChildren(v ...*Resource) *ResourceUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChildIDs(ids...)
}

// SetParent sets the "parent" edge to the Resource entity.
func (_u *ResourceUpdateOne) SetParent(v *Resource) *ResourceUpdateOne {
	return _u.SetParentID(v.ID)
}

// AddPermissionIDs adds the "permissions" edge to the Permission entity by IDs.
func (_u *ResourceUpdateOne) AddPermissionIDs(ids ...string) *ResourceUpdateOne {
	_u.mutation.AddPermissionIDs(ids...)
	return _u
}

// AddPermissions adds the "permissions" edges to the Permission entity.
func (_u *ResourceUpdateOne) AddPermissions(v ...*Permission) *ResourceUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPermissionIDs(ids...)
}

// AddPermissionResourceIDs adds the "permission_resources" edge to the PermissionResource entity by IDs.
func (_u *ResourceUpdateOne) AddPermissionResourceIDs(ids ...string) *ResourceUpdateOne {
	_u.mutation.AddPermissionResourceIDs(ids...)
	return _u
}

// AddPermissionResources adds the "permission_resources" edges to the PermissionResource entity.
func (_u *ResourceUpdateOne) AddPermissionResources(v ...*PermissionResource) *ResourceUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPermissionResourceIDs(ids...)
}

// Mutation returns the ResourceMutation object of the builder.
func (_u *ResourceUpdateOne) Mutation() *ResourceMutation {
	return _u.mutation
}

// ClearChildren clears all "children" edges to the Resource entity.
func (_u *ResourceUpdateOne) ClearChildren() *ResourceUpdateOne {
	_u.mutation.ClearChildren()
	return _u
}

// RemoveChildIDs removes the "children" edge to Resource entities by IDs.
func (_u *ResourceUpdateOne) RemoveChildIDs(ids ...string) *ResourceUpdateOne {
	_u.mutation.RemoveChildIDs(ids...)
	return _u
}

// RemoveChildren removes "children" edges to Resource entities.
func (_u *ResourceUpdateOne) RemoveChildren(v ...*Resource) *ResourceUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChildIDs(ids...)
}

// ClearParent clears the "parent" edge to the Resource entity.
func (_u *ResourceUpdateOne) ClearParent() *ResourceUpdateOne {
	_u.mutation.ClearParent()
	return _u
}

// ClearPermissions clears all "permissions" edges to the Permission entity.
func (_u *ResourceUpdateOne) ClearPermissions() *ResourceUpdateOne {
	_u.mutation.ClearPermissions()
	return _u
}

// RemovePermissionIDs removes the "permissions" edge to Permission entities by IDs.
func (_u *ResourceUpdateOne) RemovePermissionIDs(ids ...string) *ResourceUpdateOne {
	_u.mutation.RemovePermissionIDs(ids...)
	return _u
}

// RemovePermissions removes "permissions" edges to Permission entities.
func (_u *ResourceUpdateOne) RemovePermissions(v ...*Permission) *ResourceUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePermissionIDs(ids...)
}

// ClearPermissionResources clears all "permission_resources" edges to the PermissionResource entity.
func (_u *ResourceUpdateOne) ClearPermissionResources() *ResourceUpdateOne {
	_u.mutation.ClearPermissionResources()
	return _u
}

// RemovePermissionResourceIDs removes the "permission_resources" edge to PermissionResource entities by IDs.
func (_u *ResourceUpdateOne) RemovePermissionResourceIDs(ids ...string) *ResourceUpdateOne {
	_u.mutation.RemovePermissionResourceIDs(ids...)
	return _u
}

// RemovePermissionResources removes "permission_resources" edges to PermissionResource entities.
func (_u *ResourceUpdateOne) RemovePermissionResources(v ...*PermissionResource) *ResourceUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePermissionResourceIDs(ids...)
}

// Where appends a list predicates to the ResourceUpdate builder.
func (_u *ResourceUpdateOne) Where(ps ...predicate.Resource) *ResourceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ResourceUpdateOne) Select(field string, fields ...string) *ResourceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Resource entity.
func (_u *ResourceUpdateOne) Save(ctx context.Context) (*Resource, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ResourceUpdateOne) SaveX(ctx context.Context) *Resource {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ResourceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ResourceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ResourceUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ResourceUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ResourceUpdateOne) sqlSave(ctx context.Context) (_node *Resource, err error) {
	_spec := sqlgraph.NewUpdateSpec(resource.Table, resource.Columns, sqlgraph.NewFieldSpec(resource.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Resource.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, resource.FieldID)
		for _, f := range fields {
			if !resource.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != resource.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(resource.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Keyword(); ok {
		_spec.SetField(resource.FieldKeyword, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(resource.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(resource.FieldStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(resource.FieldStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(resource.FieldPath, field.TypeString, value)
	}
	if _u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resource.ChildrenTable,
			Columns: []string{resource.ChildrenColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resource.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !_u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resource.ChildrenTable,
			Columns: []string{resource.ChildrenColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resource.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resource.ChildrenTable,
			Columns: []string{resource.ChildrenColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resource.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   resource.ParentTable,
			Columns: []string{resource.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resource.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   resource.ParentTable,
			Columns: []string{resource.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resource.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   resource.PermissionsTable,
			Columns: resource.PermissionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(permission.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPermissionsIDs(); len(nodes) > 0 && !_u.mutation.PermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   resource.PermissionsTable,
			Columns: resource.PermissionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(permission.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PermissionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   resource.PermissionsTable,
			Columns: resource.PermissionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(permission.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PermissionResourcesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   resource.PermissionResourcesTable,
			Columns: []string{resource.PermissionResourcesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(permissionresource.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPermissionResourcesIDs(); len(nodes) > 0 && !_u.mutation.PermissionResourcesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   resource.PermissionResourcesTable,
			Columns: []string{resource.PermissionResourcesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(permissionresource.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PermissionResourcesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   resource.PermissionResourcesTable,
			Columns: []string{resource.PermissionResourcesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(permissionresource.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Resource{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{resource.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SetResource set the Resource
func (ru *ResourceUpdate) SetResource(input *Resource, fields ...string) *ResourceUpdate {
	m := ru.mutation
	if len(fields) == 0 {
		fields = resource.OmitColumns(resource.FieldID)
	}
	_ = m.SetFields(input, fields...)
	return ru
}

// SetResourceWithZero set the Resource
func (ru *ResourceUpdate) SetResourceWithZero(input *Resource, fields ...string) *ResourceUpdate {
	m := ru.mutation
	if len(fields) == 0 {
		fields = resource.Columns
	}
	_ = m.SetFieldsWithZero(input, fields...)
	return ru
}

// SetResource set the Resource
func (ruo *ResourceUpdateOne) SetResource(input *Resource, fields ...string) *ResourceUpdateOne {
	m := ruo.mutation
	if len(fields) == 0 {
		fields = resource.OmitColumns(resource.FieldID)
	}
	_ = m.SetFields(input, fields...)
	return ruo
}

// SetResourceWithZero set the Resource
func (ruo *ResourceUpdateOne) SetResourceWithZero(input *Resource, fields ...string) *ResourceUpdateOne {
	m := ruo.mutation
	if len(fields) == 0 {
		fields = resource.Columns
	}
	_ = m.SetFieldsWithZero(input, fields...)
	return ruo
}

// Omit allows the unselect one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
func (ruo *ResourceUpdateOne) Omit(fields ...string) *ResourceUpdateOne {
	omits := make(map[string]struct{}, len(fields))
	for i := range fields {
		omits[fields[i]] = struct{}{}
	}
	ruo.fields = []string(nil)
	for _, col := range resource.Columns {
		if _, ok := omits[col]; !ok {
			ruo.fields = append(ruo.fields, col)
		}
	}
	return ruo
}
