// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"github.com/origadmin/abgen/testdata/ent/predicate"
	"github.com/origadmin/abgen/testdata/ent/softdelete"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SoftDeleteUpdate is the builder for updating SoftDelete entities.
type SoftDeleteUpdate struct {
	config
	hooks     []Hook
	mutation  *SoftDeleteMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the SoftDeleteUpdate builder.
func (_u *SoftDeleteUpdate) Where(ps ...predicate.SoftDelete) *SoftDeleteUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDeleteTime sets the "delete_time" field.
func (_u *SoftDeleteUpdate) SetDeleteTime(v time.Time) *SoftDeleteUpdate {
	_u.mutation.SetDeleteTime(v)
	return _u
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_u *SoftDeleteUpdate) SetNillableDeleteTime(v *time.Time) *SoftDeleteUpdate {
	if v != nil {
		_u.SetDeleteTime(*v)
	}
	return _u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (_u *SoftDeleteUpdate) ClearDeleteTime() *SoftDeleteUpdate {
	_u.mutation.ClearDeleteTime()
	return _u
}

// Mutation returns the SoftDeleteMutation object of the builder.
func (_u *SoftDeleteUpdate) Mutation() *SoftDeleteMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SoftDeleteUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SoftDeleteUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SoftDeleteUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SoftDeleteUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *SoftDeleteUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SoftDeleteUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *SoftDeleteUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(softdelete.Table, softdelete.Columns, sqlgraph.NewFieldSpec(softdelete.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DeleteTime(); ok {
		_spec.SetField(softdelete.FieldDeleteTime, field.TypeTime, value)
	}
	if _u.mutation.DeleteTimeCleared() {
		_spec.ClearField(softdelete.FieldDeleteTime, field.TypeTime)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{softdelete.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SoftDeleteUpdateOne is the builder for updating a single SoftDelete entity.
type SoftDeleteUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *SoftDeleteMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetDeleteTime sets the "delete_time" field.
func (_u *SoftDeleteUpdateOne) SetDeleteTime(v time.Time) *SoftDeleteUpdateOne {
	_u.mutation.SetDeleteTime(v)
	return _u
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_u *SoftDeleteUpdateOne) SetNillableDeleteTime(v *time.Time) *SoftDeleteUpdateOne {
	if v != nil {
		_u.SetDeleteTime(*v)
	}
	return _u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (_u *SoftDeleteUpdateOne) ClearDeleteTime() *SoftDeleteUpdateOne {
	_u.mutation.ClearDeleteTime()
	return _u
}

// Mutation returns the SoftDeleteMutation object of the builder.
func (_u *SoftDeleteUpdateOne) Mutation() *SoftDeleteMutation {
	return _u.mutation
}

// Where appends a list predicates to the SoftDeleteUpdate builder.
func (_u *SoftDeleteUpdateOne) Where(ps ...predicate.SoftDelete) *SoftDeleteUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SoftDeleteUpdateOne) Select(field string, fields ...string) *SoftDeleteUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SoftDelete entity.
func (_u *SoftDeleteUpdateOne) Save(ctx context.Context) (*SoftDelete, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SoftDeleteUpdateOne) SaveX(ctx context.Context) *SoftDelete {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SoftDeleteUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SoftDeleteUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *SoftDeleteUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SoftDeleteUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *SoftDeleteUpdateOne) sqlSave(ctx context.Context) (_node *SoftDelete, err error) {
	_spec := sqlgraph.NewUpdateSpec(softdelete.Table, softdelete.Columns, sqlgraph.NewFieldSpec(softdelete.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SoftDelete.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, softdelete.FieldID)
		for _, f := range fields {
			if !softdelete.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != softdelete.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DeleteTime(); ok {
		_spec.SetField(softdelete.FieldDeleteTime, field.TypeTime, value)
	}
	if _u.mutation.DeleteTimeCleared() {
		_spec.ClearField(softdelete.FieldDeleteTime, field.TypeTime)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &SoftDelete{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{softdelete.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SetSoftDelete set the SoftDelete
func (sdu *SoftDeleteUpdate) SetSoftDelete(input *SoftDelete, fields ...string) *SoftDeleteUpdate {
	m := sdu.mutation
	if len(fields) == 0 {
		fields = softdelete.OmitColumns(softdelete.FieldID)
	}
	_ = m.SetFields(input, fields...)
	return sdu
}

// SetSoftDeleteWithZero set the SoftDelete
func (sdu *SoftDeleteUpdate) SetSoftDeleteWithZero(input *SoftDelete, fields ...string) *SoftDeleteUpdate {
	m := sdu.mutation
	if len(fields) == 0 {
		fields = softdelete.Columns
	}
	_ = m.SetFieldsWithZero(input, fields...)
	return sdu
}

// SetSoftDelete set the SoftDelete
func (sduo *SoftDeleteUpdateOne) SetSoftDelete(input *SoftDelete, fields ...string) *SoftDeleteUpdateOne {
	m := sduo.mutation
	if len(fields) == 0 {
		fields = softdelete.OmitColumns(softdelete.FieldID)
	}
	_ = m.SetFields(input, fields...)
	return sduo
}

// SetSoftDeleteWithZero set the SoftDelete
func (sduo *SoftDeleteUpdateOne) SetSoftDeleteWithZero(input *SoftDelete, fields ...string) *SoftDeleteUpdateOne {
	m := sduo.mutation
	if len(fields) == 0 {
		fields = softdelete.Columns
	}
	_ = m.SetFieldsWithZero(input, fields...)
	return sduo
}

// Omit allows the unselect one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
func (sduo *SoftDeleteUpdateOne) Omit(fields ...string) *SoftDeleteUpdateOne {
	omits := make(map[string]struct{}, len(fields))
	for i := range fields {
		omits[fields[i]] = struct{}{}
	}
	sduo.fields = []string(nil)
	for _, col := range softdelete.Columns {
		if _, ok := omits[col]; !ok {
			sduo.fields = append(sduo.fields, col)
		}
	}
	return sduo
}
