// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"github.com/origadmin/abgen/testdata/ent/softdelete"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// SoftDelete is the model entity for the SoftDelete schema.
type SoftDelete struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// delete_time.field.comment
	DeleteTime   *time.Time `json:"delete_time,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SoftDelete) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case softdelete.FieldID:
			values[i] = new(sql.NullInt64)
		case softdelete.FieldDeleteTime:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SoftDelete fields.
func (_m *SoftDelete) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case softdelete.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case softdelete.FieldDeleteTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field delete_time", values[i])
			} else if value.Valid {
				_m.DeleteTime = new(time.Time)
				*_m.DeleteTime = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SoftDelete.
// This includes values selected through modifiers, order, etc.
func (_m *SoftDelete) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this SoftDelete.
// Note that you need to call SoftDelete.Unwrap() before calling this method if this SoftDelete
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SoftDelete) Update() *SoftDeleteUpdateOne {
	return NewSoftDeleteClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SoftDelete entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SoftDelete) Unwrap() *SoftDelete {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SoftDelete is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SoftDelete) String() string {
	var builder strings.Builder
	builder.WriteString("SoftDelete(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.DeleteTime; v != nil {
		builder.WriteString("delete_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// SoftDeletes is a parsable slice of SoftDelete.
type SoftDeletes []*SoftDelete
