// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"github.com/origadmin/abgen/testdata/ent/predicate"
	"github.com/origadmin/abgen/testdata/ent/softdelete"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SoftDeleteDelete is the builder for deleting a SoftDelete entity.
type SoftDeleteDelete struct {
	config
	hooks    []Hook
	mutation *SoftDeleteMutation
}

// Where appends a list predicates to the SoftDeleteDelete builder.
func (_d *SoftDeleteDelete) Where(ps ...predicate.SoftDelete) *SoftDeleteDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *SoftDeleteDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SoftDeleteDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *SoftDeleteDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(softdelete.Table, sqlgraph.NewFieldSpec(softdelete.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// SoftDeleteDeleteOne is the builder for deleting a single SoftDelete entity.
type SoftDeleteDeleteOne struct {
	_d *SoftDeleteDelete
}

// Where appends a list predicates to the SoftDeleteDelete builder.
func (_d *SoftDeleteDeleteOne) Where(ps ...predicate.SoftDelete) *SoftDeleteDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *SoftDeleteDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{softdelete.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SoftDeleteDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
