// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"github.com/origadmin/abgen/testdata/ent/predicate"
	"github.com/origadmin/abgen/testdata/ent/softdelete"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SoftDeleteQuery is the builder for querying SoftDelete entities.
type SoftDeleteQuery struct {
	config
	ctx        *QueryContext
	order      []softdelete.OrderOption
	inters     []Interceptor
	predicates []predicate.SoftDelete
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SoftDeleteQuery builder.
func (_q *SoftDeleteQuery) Where(ps ...predicate.SoftDelete) *SoftDeleteQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *SoftDeleteQuery) Limit(limit int) *SoftDeleteQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *SoftDeleteQuery) Offset(offset int) *SoftDeleteQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *SoftDeleteQuery) Unique(unique bool) *SoftDeleteQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *SoftDeleteQuery) Order(o ...softdelete.OrderOption) *SoftDeleteQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// First returns the first SoftDelete entity from the query.
// Returns a *NotFoundError when no SoftDelete was found.
func (_q *SoftDeleteQuery) First(ctx context.Context) (*SoftDelete, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{softdelete.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *SoftDeleteQuery) FirstX(ctx context.Context) *SoftDelete {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SoftDelete ID from the query.
// Returns a *NotFoundError when no SoftDelete ID was found.
func (_q *SoftDeleteQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{softdelete.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *SoftDeleteQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SoftDelete entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SoftDelete entity is found.
// Returns a *NotFoundError when no SoftDelete entities are found.
func (_q *SoftDeleteQuery) Only(ctx context.Context) (*SoftDelete, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{softdelete.Label}
	default:
		return nil, &NotSingularError{softdelete.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *SoftDeleteQuery) OnlyX(ctx context.Context) *SoftDelete {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SoftDelete ID in the query.
// Returns a *NotSingularError when more than one SoftDelete ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *SoftDeleteQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{softdelete.Label}
	default:
		err = &NotSingularError{softdelete.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *SoftDeleteQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SoftDeletes.
func (_q *SoftDeleteQuery) All(ctx context.Context) ([]*SoftDelete, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SoftDelete, *SoftDeleteQuery]()
	return withInterceptors[[]*SoftDelete](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *SoftDeleteQuery) AllX(ctx context.Context) []*SoftDelete {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SoftDelete IDs.
func (_q *SoftDeleteQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(softdelete.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *SoftDeleteQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *SoftDeleteQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*SoftDeleteQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *SoftDeleteQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *SoftDeleteQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *SoftDeleteQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SoftDeleteQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *SoftDeleteQuery) Clone() *SoftDeleteQuery {
	if _q == nil {
		return nil
	}
	return &SoftDeleteQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]softdelete.OrderOption{}, _q.order...),
		inters:     append([]Interceptor{}, _q.inters...),
		predicates: append([]predicate.SoftDelete{}, _q.predicates...),
		// clone intermediate query.
		sql:       _q.sql.Clone(),
		path:      _q.path,
		modifiers: append([]func(*sql.Selector){}, _q.modifiers...),
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		DeleteTime time.Time `json:"delete_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SoftDelete.Query().
//		GroupBy(softdelete.FieldDeleteTime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *SoftDeleteQuery) GroupBy(field string, fields ...string) *SoftDeleteGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SoftDeleteGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = softdelete.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		DeleteTime time.Time `json:"delete_time,omitempty"`
//	}
//
//	client.SoftDelete.Query().
//		Select(softdelete.FieldDeleteTime).
//		Scan(ctx, &v)
func (_q *SoftDeleteQuery) Select(fields ...string) *SoftDeleteSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &SoftDeleteSelect{SoftDeleteQuery: _q}
	sbuild.label = softdelete.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SoftDeleteSelect configured with the given aggregations.
func (_q *SoftDeleteQuery) Aggregate(fns ...AggregateFunc) *SoftDeleteSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *SoftDeleteQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !softdelete.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *SoftDeleteQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SoftDelete, error) {
	var (
		nodes = []*SoftDelete{}
		_spec = _q.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SoftDelete).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SoftDelete{config: _q.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (_q *SoftDeleteQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *SoftDeleteQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(softdelete.Table, softdelete.Columns, sqlgraph.NewFieldSpec(softdelete.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, softdelete.FieldID)
		for i := range fields {
			if fields[i] != softdelete.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *SoftDeleteQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(softdelete.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = softdelete.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *SoftDeleteQuery) ForUpdate(opts ...sql.LockOption) *SoftDeleteQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *SoftDeleteQuery) ForShare(opts ...sql.LockOption) *SoftDeleteQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_q *SoftDeleteQuery) Modify(modifiers ...func(s *sql.Selector)) *SoftDeleteSelect {
	_q.modifiers = append(_q.modifiers, modifiers...)
	return _q.Select()
}

// Omit allows the unselect one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
// Example:
//
//	var v []struct {
//	  DeleteTime time.Time `json:"delete_time,omitempty"`
//	}
//
//	client.SoftDelete.Query().
//	  Omit(
//	  softdelete.FieldDeleteTime,
//	  ).
//	  Scan(ctx, &v)
func (sdq *SoftDeleteQuery) Omit(fields ...string) *SoftDeleteSelect {
	omits := make(map[string]struct{}, len(fields))
	for i := range fields {
		omits[fields[i]] = struct{}{}
	}
	for _, col := range softdelete.Columns {
		if _, ok := omits[col]; !ok {
			sdq.ctx.Fields = append(sdq.ctx.Fields, col)
		}
	}

	sbuild := &SoftDeleteSelect{SoftDeleteQuery: sdq}
	sbuild.label = softdelete.Label
	sbuild.flds, sbuild.scan = &sdq.ctx.Fields, sbuild.Scan
	return sbuild
}

// SoftDeleteGroupBy is the group-by builder for SoftDelete entities.
type SoftDeleteGroupBy struct {
	selector
	build *SoftDeleteQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *SoftDeleteGroupBy) Aggregate(fns ...AggregateFunc) *SoftDeleteGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *SoftDeleteGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SoftDeleteQuery, *SoftDeleteGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *SoftDeleteGroupBy) sqlScan(ctx context.Context, root *SoftDeleteQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SoftDeleteSelect is the builder for selecting fields of SoftDelete entities.
type SoftDeleteSelect struct {
	*SoftDeleteQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *SoftDeleteSelect) Aggregate(fns ...AggregateFunc) *SoftDeleteSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *SoftDeleteSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SoftDeleteQuery, *SoftDeleteSelect](ctx, _s.SoftDeleteQuery, _s, _s.inters, v)
}

func (_s *SoftDeleteSelect) sqlScan(ctx context.Context, root *SoftDeleteQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_s *SoftDeleteSelect) Modify(modifiers ...func(s *sql.Selector)) *SoftDeleteSelect {
	_s.modifiers = append(_s.modifiers, modifiers...)
	return _s
}
