// Code generated by alias-binding. DO NOT EDIT.

package {{.Package}}

import (
{{range $key, $val := .Imports}}
	{{$key}} "{{$val}}"
{{end}}
)

{{- define "type_aliases" -}}
{{- if .TypeAliases -}}
type (
{{- range $alias, $info := .TypeAliases}}
    {{- if and $info.ImportAlias (ne $info.ImportAlias ".")}}
	{{$alias}} = {{$info.ImportAlias}}.{{$info.Name}}
    {{- else}}
    {{$alias}} = {{$info.Name}}
    {{- end}}
{{- end}}
)
{{- end -}}
{{- end -}}

{{template "type_aliases" .}}

{{range .Converters}}
	// {{.FuncName}} converts {{.SourceAlias}} to {{.TargetAlias}}
	func {{.FuncName}}(src *{{.SourceAlias}}) *{{.TargetAlias}} {
	dst := &{{.TargetAlias}}{}
	if src == nil {
		return dst
	}

	{{range .Fields -}}
	{{if .Ignore}}// ignore: {{.Name}} {{.IgnoreReason}}
	{{else}}{{.Conversion}}
	{{end -}}
	{{end}}
	return dst
	}
{{end}}
