// Code generated by abgen. DO NOT EDIT.
// versions:
// 	abgen v0.0.1

package {{ .PackageName }}

import (
{{- range .Imports }}
	{{ .Alias }} "{{ .Path }}"
{{- end }}
)

{{- if .TypeAliases }}

// Auto-generated type aliases.
{{- range .TypeAliases }}
{{ . }}
{{- end }}
{{- end }}

{{- range .Funcs }}

// {{ .Name }} converts {{ .SourcePointer }}{{ .SourceType }} to {{ .TargetPointer }}{{ .TargetType }}.
func {{ .Name }}(src {{ .SourcePointer }}{{ .SourceType }}) {{ .TargetPointer }}{{ .TargetType }} {
	if src == nil {
		return nil
	}
	dst := &{{ .TargetType }}{}
	{{- range .Conversions }}
	{{ .Conversion }}
	{{- end }}
	return dst
}
{{- end }}
{{- end -}}