// Code generated by alias-binding. DO NOT EDIT.

package {{.Package}}

import (
{{range $key, $val := .Imports}}
	{{$key}} "{{$val}}"
{{end}}
)

{{range .Converters}}
	// {{.FuncName}} converts {{.SourceAlias}} to {{.TargetAlias}}
	func {{.FuncName}}(src *{{.SourceAlias}}) *{{.TargetAlias}} {
	dst := &{{.TargetAlias}}{}
	if src == nil {
		return dst
	}

	{{range .Fields -}}
	{{if .Ignore}}// ignore: {{.Name}} {{.IgnoreReason}}
	{{else}}{{.Conversion}}
	{{end -}}
	{{end}}
	return dst
	}
{{end}}
